version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../../"
    schedule:
      interval: "dayli"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "express"
        versions: ["4.x.x"]
